#!/bin/bash
# ================== Disclamer ================== #
#                                                 #
# When running this script, It will OVERRITE      #
# your old configuration!                         #
# Please, take a backup if you're not sure        #
# of the new configurations.                      #
#                                                 #
# Note that the seconderyPrivateIPs should be     #
# seperated by commas like the following example: #
# "seconderyPrivateIPs" : "1.1.1.1,2.2.2.2"       #
# =============================================== #

tenancyId=""
authUserId=""
keyFingerprint=""
tenancyRegion=""

# =========== Make Your changes Here ============ #
JSON='{
  "vnic_1" : {
    "name" : "",
    "ocid" : "",
    "seconderyPrivateIPs" : "<seconderyPrivateIPs>"
  },
  "vnic_2" : {
    "name" : "",
    "ocid" : "",
    "seconderyPrivateIPs" : "<seconderyPrivateIPs>"
  },
  "vnic_3" : {
    "name" : "",
    "ocid" : "",
    "seconderyPrivateIPs" : "<seconderyPrivateIPs>"
  },
  "vnic_4" : {
    "name" : "",
    "ocid" : "",
    "seconderyPrivateIPs" : "<seconderyPrivateIPs>"
  },
  "vnic_5" : {
    "name" : "",
    "ocid" : "",
    "seconderyPrivateIPs" : "<seconderyPrivateIPs>"
  },
  "vnic_6" : {
    "name" : "",
    "ocid" : "",
    "seconderyPrivateIPs" : "<seconderyPrivateIPs>"
  }
}'
# ============ Nevermind The Rest :) ============ #
js () {
  jq -r ".$1" <<< "$JSON"
}


# Dowloading the bash script template
curl https://raw.githubusercontent.com/alwisidi/f5-oci-failover/master/oci-curl -o /config/failover/oci-curl
chmod +x /config/failover/oci-curl

# Modifying Authentication Parameters
sed -Ei "s/^(.*local tenancyId=\").*(\";)$/\1$tenancyId\2/" /config/failover/oci-curl
sed -Ei "s/^(.*local authUserId=\").*(\";)$/\1$authUserId\2/" /config/failover/oci-curl
sed -Ei "s/^(.*local keyFingerprint=\").*(\";)$/\1$keyFingerprint\2/" /config/failover/oci-curl

# Creating JSON Objects for Source VNICs
for i in {1..6}; do
  echo -e "{\n\s\s\"vnicId\"\s:\s\"$(js vnic_$i.ocid)\"\n}" > /config/failover/$(js vnic_$i.name)
done

# Downloading the active file template
printf '%s\n' '13,$d' w | ed file1 2&>1 /dev/null
curl https://raw.githubusercontent.com/alwisidi/f5-oci-failover/master/tgactive >> /config/failover/tgactive

# Configuring the sources and targets for failing-over
for i in {1..6}; do
  IFS=',' read -ra ips <<< $(js vnic_$i.seconderyPrivateIPs)
  for ip in ${ips[@]}; do
    TMP="/config/failover/oci-curl iaas.$tenancyRegion\.oraclecloud.com PUT /config/failover/$(js vnic_$i.name).json \"/20160918/privateIps/$ip\""
    sed -Ei "/END/s/^/$TMP\n/" /config/failover/tgactive
  done
done