#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/var/log/messages 2>&1
logger -p local0.notice "$0 traffic-group-1 : Started."
# ====================== START ====================== #

# ======================= END ======================= #
logger -p local0.notice "$0 traffic-group-1: Finished."
